# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('picUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
